const translations={
 en:{navFeatured:'Featured',navGuardians:'Guardians',navInspirations:'Inspirations',navLuminous:'Luminous',navAbout:'About',navContact:'Contact',heroEyebrow:'Contemporary symbolic realism',heroLead:'Traditional drawing and digital illumination meet in works exploring nature, vulnerability, memory and transformation.',featuredTitle:'Featured Works',featuredIntro:'Three works that open the door to the ideas, emotions and visual language behind the portfolio.',guardTitle:'Guardians of Light',guardIntro:'An ongoing conservation art project: endangered species portrayed through luminous threads, with a direct path from each artwork to the people working to protect the species.',guardMissionLabel:'Project mission',guardMissionText:'Guardians of Light combines traditional drawing with digital illumination to make threatened species harder to overlook. The goal is a 20-piece series that connects visual attention with conservation awareness and support.',guardMethod:'Each portrait begins on 30 × 40 cm Clairefontaine Pastelmat with Faber-Castell Polychromos pencils, then receives its final light in Autodesk Sketchbook.',guardGoal:'planned portraits',guardStatus:'endangered species',guardAction:'conservation links',guardDisclaimer:'Conservation links point to independent organizations working for the species or its habitat. Inclusion does not imply a formal partnership unless explicitly stated.',guardianMore:'Story & conservation',guardianModalLabel:'Guardian profile',guardianStoryTitle:'The species & the artwork',guardianConservationTitle:'Conservation links',guardianOrgIntro:'Organizations and projects working on the species or its habitat:',gSlothShort:"One of the world's rarest mammals, restricted to a single small island in Panama.",gTapanuliShort:'The rarest great ape, surviving only in the Batang Toru ecosystem of Sumatra.',gCatShort:"One of the world's least-known wild cats, scattered across the high Andes.",gPangolinShort:"Nature's armor offers no defense against poaching and illegal wildlife trade.",gMacawShort:'A Bolivian endemic pushed close to extinction by habitat loss and the wild-bird trade.',gAxolotlShort:'A master of regeneration whose wild future depends on restoring Xochimilco.',inspirationTitle:'Unique Inspirations',inspirationIntro:'Independent narrative works shaped by symbolism, social observation and magical realism.',luminousTitle:'Luminous Visions',luminousIntro:'Experimental portraits and figurative studies where light became a visual language—and eventually gave rise to Guardians of Light.',aboutTitle:'About the Artist',contactTitle:'Get in Touch',contactText:'For exhibitions, conservation collaborations, commissions or general inquiries.',sendEmail:'Send an email'},
 hu:{navFeatured:'Kiemelt művek',navGuardians:'A Fény Őrzői',navInspirations:'Egyedi inspirációk',navLuminous:'Fénylő látomások',navAbout:'Rólam',navContact:'Kapcsolat',heroEyebrow:'Kortárs szimbolikus realizmus',heroLead:'Hagyományos rajz és digitális fény ötvözésével készítek természetközpontú és szimbolikus képeket.',featuredTitle:'Kiemelt művek',featuredIntro:'Három alkotás, amely kaput nyit a portfólió gondolataihoz, érzelmeihez és vizuális nyelvéhez.',guardTitle:'A Fény Őrzői',guardIntro:'Folyamatos természetvédelmi művészeti projekt: veszélyeztetett fajok fényfonalas portréi, közvetlen kapcsolattal az értük dolgozó szervezetekhez.',guardMissionLabel:'A projekt célja',guardMissionText:'A Fény Őrzői a hagyományos rajzot és a digitális fényt kapcsolja össze, hogy a veszélyeztetett fajokat ne lehessen egyszerűen figyelmen kívül hagyni. A cél egy 20 darabos sorozat, amely a vizuális figyelmet természetvédelmi tudatossággal és támogatással köti össze.',guardMethod:'Minden portré 30 × 40 cm-es Clairefontaine Pastelmat papíron, Faber-Castell Polychromos ceruzákkal indul, majd Autodesk Sketchbookban kapja meg a végső fényt.',guardGoal:'tervezett portré',guardStatus:'veszélyeztetett fajok',guardAction:'természetvédelmi linkek',guardDisclaimer:'A természetvédelmi linkek a fajért vagy élőhelyéért dolgozó független szervezetekhez vezetnek. A feltüntetés önmagában nem jelent hivatalos együttműködést.',guardianMore:'Történet és természetvédelem',guardianModalLabel:'Az Őrző adatlapja',guardianStoryTitle:'A faj és az alkotás',guardianConservationTitle:'Természetvédelmi linkek',guardianOrgIntro:'A fajért vagy élőhelyéért dolgozó szervezetek és programok:',gSlothShort:'A világ egyik legritkább emlőse, amelynek teljes vadon élő állománya Panama egyetlen apró szigetére korlátozódik.',gTapanuliShort:'A legritkább emberszabású, amely csak Szumátra Batang Toru ökoszisztémájában él.',gCatShort:'A világ egyik legritkább és legkevésbé ismert vadmacskája, az Andok magashegyi vidékein.',gPangolinShort:'A természet páncélja sem védi meg az orvvadászattól és az illegális állatkereskedelemtől.',gMacawShort:'Bolívia bennszülött papagájfaja, amelyet az élőhelyvesztés és a madárkereskedelem sodort a kihalás szélére.',gAxolotlShort:'A regeneráció mestere, amelynek vadonbeli jövője Xochimilco helyreállításától függ.',inspirationTitle:'Egyedi inspirációk',inspirationIntro:'Önálló narratív alkotások szimbolizmussal, társadalmi megfigyeléssel és mágikus realizmussal.',luminousTitle:'Luminous Visions',luminousIntro:'Kísérleti portrék és figurális tanulmányok, amelyekben a fény vizuális nyelvvé vált—és amelyekből később megszületett A Fény Őrzői.',aboutTitle:'Az alkotóról',contactTitle:'Kapcsolat',contactText:'Kiállítások, természetvédelmi együttműködések, megbízások vagy általános megkeresések.',sendEmail:'E-mail küldése'}
};

Object.assign(translations.en,{
 navInspirations:'Works',inspirationTitle:'Narrative Works',luminousTitle:'Luminous Visions',drawingWithLight:'Drawing with Light',guardPrimary:'Primary Project · 6 / 20 completed',guardGoal:'portraits completed',iucnCR:'CR · Critically Endangered',iucnEN:'EN · Endangered',guardianStoryTitle:'Species, threats & the artwork',recognitionTitle:'Selected Recognition',youngAward:'2nd Prize · Zsilip national art competition',selfieAward:'Selected for Exhibition, Top 20 · Zsilip national thematic competition',youngAwardMeta:'2025 · 2nd Prize · National competition',selfieAwardMeta:'2025 · Colored pencil · National exhibition selection, Top 20',apexLabel:'First animal glow study',apexText:'Created from my first animal drawing, Apex Glow became my first experiment with applying digital light to an animal portrait—and an early bridge toward Guardians of Light.',apexCompare:'Original graphite / Glow study',processLabel:'Process study',processTitle:'From Drawing to Light',processIntro:'A rare four-stage record of one work evolving from line drawing through graphite modelling and selective illumination to its final colour and atmosphere.',processStage1:'Line drawing',processStage2:'Graphite modelling',processStage3:'First light layer',processStage4:'Final colour'
});
Object.assign(translations.hu,{
 navInspirations:'Művek',inspirationTitle:'Narratív művek',luminousTitle:'Fénylő látomások',drawingWithLight:'Fénnyel rajzolva',guardPrimary:'Fő projekt · 6 / 20 elkészült',guardGoal:'elkészült portré',iucnCR:'CR · Súlyosan veszélyeztetett',iucnEN:'EN · Veszélyeztetett',guardianStoryTitle:'A faj, a veszélyek és az alkotás',recognitionTitle:'Válogatott eredmények',youngAward:'2. helyezés · Zsilip országos képzőművészeti pályázat',selfieAward:'Kiállításra válogatva, legjobb 20 · Zsilip országos tematikus pályázat',youngAwardMeta:'2025 · 2. helyezés · Országos pályázat',selfieAwardMeta:'2025 · Színes ceruza · Országos kiállítási válogatás, legjobb 20',apexLabel:'Az első állati glow-kísérlet',apexText:'Az első állatrajzomból született Apex Glow volt az első kísérletem, amelyben digitális fényt alkalmaztam egy állatportrén — és korai hidat teremtett A Fény Őrzői felé.',apexCompare:'Eredeti grafit / Glow-kísérlet',processLabel:'Munkafolyamat',processTitle:'A rajztól a fényig',processIntro:'Egy mű kivételes, négyfázisú dokumentációja: a vonalrajztól a grafittónusokon és a szelektív megvilágításon át a végleges szín- és atmoszféravilágig.',processStage1:'Vonalrajz',processStage2:'Grafittónusok',processStage3:'Az első fényréteg',processStage4:'Végleges színvilág'
});

// Keep the primary project directly after the opening statement.
const heroSection=document.querySelector('.hero'),guardiansSection=document.querySelector('#guardians');
if(heroSection&&guardiansSection)heroSection.after(guardiansSection);

const guardianDetails={
 sloth:{scientific:'Bradypus pygmaeus',en:{title:'Pygmy Three-Toed Sloth',story:["The first Guardian of Light is a small, almost whimsical-looking sloth found naturally nowhere except Isla Escudo de Veraguas, a tiny island off Panama’s Caribbean coast.","Its entire wild range is confined to this single island. Habitat disturbance and the loss of coastal mangroves therefore affect not merely one population, but the future of the whole species.","Conservation and research organisations are working to understand and protect this exceptionally restricted animal. The portrait asks for the same first step from its viewer: attention—because what remains visible may still be protected."],orgs:[['The Sloth Conservation Foundation (SloCo)','Sloth conservation, research and public awareness','https://www.slothconservation.org/blog/the-pygmy-sloths-of-panama']]},hu:{title:'Törpe háromujjú lajhár',story:['A Fény Őrzői első darabja ez a nagyjából macska méretű, szinte bohókás külsejű lajhár, amely természetes körülmények között kizárólag a Panama karibi partjainál fekvő Escudo de Veraguas apró szigetén él.','Teljes vadonbeli elterjedése erre az egyetlen szigetre korlátozódik. Az élőhely megbolygatása és a part menti mangroveerdők pusztulása ezért nem csupán egy állományt, hanem az egész faj jövőjét veszélyezteti.','Természetvédelmi és kutatási szervezetek dolgoznak e rendkívül szűk elterjedésű állat megismerésén és védelmén. A portré ugyanezt az első lépést kéri a nézőtől: figyelmet — mert amit még látunk, azt még megőrizhetjük.'],orgs:[['The Sloth Conservation Foundation (SloCo)','Lajhárvédelem, kutatás és ismeretterjesztés','https://www.slothconservation.org/blog/the-pygmy-sloths-of-panama']]}},
 tapanuli:{scientific:'Pongo tapanuliensis',en:{title:'Tapanuli Orangutan',story:['Recognised as a distinct species only in 2017, the Tapanuli orangutan is the rarest great ape on Earth. It survives only in a small, fragmented part of the Batang Toru ecosystem in northern Sumatra.','Habitat fragmentation, illegal logging and infrastructure development continue to threaten it. In such a small and isolated range, every lost section of forest can have an irreversible effect on the species’ future.','Research, habitat protection and work with local communities keep that future open. In the portrait, light becomes continuity: a fragile connection between an ancient lineage and the forest on which its survival still depends.'],orgs:[['Sumatran Orangutan Conservation Programme (SOCP)','Research, monitoring and conservation in Sumatra and Batang Toru','https://sumatranorangutan.org/what-we-do/biodiversity-monitoring-research-and-surveys/']]},hu:{title:'Tapanuli orangután',story:['A csak 2017-ben önálló fajként leírt tapanuli orangután a Föld legritkább emberszabásúja. Kizárólag Észak-Szumátra Batang Toru ökoszisztémájának kis, feldarabolódott területén maradt fenn.','Fennmaradását az élőhelyek feldarabolása, az illegális fakitermelés és az infrastruktúra-fejlesztések veszélyeztetik. Egy ennyire kis és elszigetelt területen minden elveszített erdőrészlet visszafordíthatatlan hatással lehet a faj jövőjére.','A kutatás, az élőhelyvédelem és a helyi közösségekkel végzett munka még nyitva tartja ezt a jövőt. A portréban a fény a folytonosság jelképe: törékeny kapcsolat egy ősi fejlődési ág és az erdő között, amelytől a fennmaradása ma is függ.'],orgs:[['Sumatran Orangutan Conservation Programme (SOCP)','Kutatás, monitoring és természetvédelem Szumátrán és Batang Toruban','https://sumatranorangutan.org/what-we-do/biodiversity-monitoring-research-and-surveys/']]}},
 andean:{scientific:'Leopardus jacobita',en:{title:'Andean Mountain Cat',story:['The Andean cat is one of the rarest and least-known wild cats in the world. Its isolated populations inhabit remote high-altitude landscapes across Argentina, Bolivia, Chile and Peru.','Its elusive behaviour and difficult terrain make even population estimates a challenge. Habitat fragmentation, mining and infrastructure development, declining prey and conflict with people all threaten its survival.','The Andean Cat Alliance works with researchers, conservationists and local communities to prevent this almost invisible species from disappearing unnoticed. In the portrait, the surrounding darkness reflects how little is still known about its population and future.'],orgs:[['Andean Cat Alliance / Alianza Gato Andino','Species-focused research, community work and habitat conservation','https://gatoandino.org/en/about-us/']]},hu:{title:'Andoki macska',story:['Az andoki macska a világ egyik legritkább és legkevésbé ismert vadmacskája. Elszigetelt populációi Argentína, Bolívia, Chile és Peru távoli magashegyi vidékein élnek.','Rejtőzködő életmódja és nehezen megközelíthető élőhelye miatt még az állomány nagyságát is nehéz felmérni. Fennmaradását az élőhelyek feldarabolása, a bányászat és az infrastruktúra-fejlesztések, a zsákmányállatok csökkenése, valamint az emberrel való konfliktus veszélyeztetik.','Az Andean Cat Alliance kutatókkal, természetvédelmi szakemberekkel és helyi közösségekkel dolgozik azon, hogy ez a szinte láthatatlan faj ne tűnjön el észrevétlenül. A portrén az állatot körülvevő sötétség azt jelképezi, milyen keveset tudunk még az állományáról és a jövőjéről.'],orgs:[['Andean Cat Alliance / Alianza Gato Andino','Fajspecifikus kutatás, közösségi programok és élőhelyvédelem','https://gatoandino.org/en/about-us/']]}},
 pangolin:{scientific:'Manis pentadactyla',en:{title:'Chinese Pangolin',story:["The pangolin is one of nature’s strangest mammals—the only one protected from head to tail by hard scales. For millions of years that armour was enough. Today, it is not.","Its scales protect it from natural predators, but not from people. Poaching, illegal trade and habitat loss have caused a severe decline, and pangolins are among the most heavily trafficked wild mammals on Earth.","Save Pangolins and the IUCN SSC Pangolin Specialist Group support research, field conservation and cooperation with local communities. The portrait’s contradiction is deliberate: nature created remarkable armour, while the thread of light becomes the protection that armour can no longer provide."],orgs:[['Save Pangolins','Global public awareness and support for field conservation','https://www.savepangolins.org/'],['IUCN SSC Pangolin Specialist Group','Science, Red List assessment and global conservation strategy','https://pangolinsg.org/']]},hu:{title:'Kínai tobzoska',story:['A tobzoska az élővilág egyik legkülönösebb emlőse — az egyetlen, amelyet tetőtől talpig kemény pikkelypáncél borít. Ez a védelem évmilliókon át elegendő volt. Ma már nem az.','Pikkelyei megvédik a természetes ragadozóktól, az embertől azonban nem. Az orvvadászat, az illegális kereskedelem és az élőhelyvesztés súlyos állománycsökkenést okozott; a tobzoskák a Föld legtöbbet csempészett vadon élő emlősei közé tartoznak.','A Save Pangolins és az IUCN SSC Pangolin Specialist Group kutatással, terepi fajvédelemmel és a helyi közösségekkel együttműködve dolgozik értük. A portré ellentéte szándékos: a természet rendkívüli páncélt alkotott, a fényfonal pedig azt a védelmet jelképezi, amelyet ez a páncél már nem képes megadni.'],orgs:[['Save Pangolins','Nemzetközi figyelemfelkeltés és terepi természetvédelmi programok támogatása','https://www.savepangolins.org/'],['IUCN SSC Pangolin Specialist Group','Kutatás, Vörös Lista-értékelés és globális védelmi stratégia','https://pangolinsg.org/']]}},
 macaw:{scientific:'Ara glaucogularis',en:{title:'Blue-throated Macaw',story:['The Blue-throated Macaw is one of the world’s rarest parrots and occurs naturally only in Bolivia. Once spread across broad savannas and palm groves, it now survives in a small number of isolated populations.','Its vivid blue-and-gold plumage and distinctive blue throat are among nature’s most spectacular designs—and helped make it desirable in the exotic bird trade. Habitat loss, historic capture and a shortage of suitable nest sites pushed the species close to extinction.','Asociación Armonía and its partners protect habitat, guard nests, install nest boxes and work with local communities. The portrait’s final thought is literal as well as symbolic: when a colour like this disappears from the wild, the world becomes one shade greyer.'],orgs:[['Asociación Armonía','Habitat protection, nest-box programmes and recovery work in Bolivia','https://armoniabolivia.org/']]},hu:{title:'Kéktorkú ara',story:['A kéktorkú ara a világ egyik legritkább papagája, és természetes körülmények között kizárólag Bolíviában él. Egykor kiterjedt szavannákon és pálmaligetekben fordult elő, ma azonban már csak néhány elszigetelt populáció maradt fenn.','Élénk kék és arany tollazata, valamint jellegzetes kék torokfoltja a természet egyik leglátványosabb alkotása — és hozzájárult ahhoz is, hogy keresetté váljon az egzotikusmadár-kereskedelemben. Az élőhelyvesztés, a korábbi befogások és a megfelelő fészkelőhelyek hiánya a kihalás szélére sodorták.','Az Asociación Armonía és partnerei élőhelyvédelemmel, fészekőrzéssel, mesterséges fészkekkel és a helyi közösségekkel együttműködve dolgoznak a fajért. A portré zárógondolata egyszerre szó szerinti és jelképes: amikor egy ilyen szín eltűnik a vadonból, a világ egy árnyalattal szürkébbé válik.'],orgs:[['Asociación Armonía','Élőhelyvédelem, mesterséges fészkek és fajmegőrzési programok Bolíviában','https://armoniabolivia.org/']]}},
 axolotl:{scientific:'Ambystoma mexicanum',en:{title:'Axolotl',story:['The axolotl is one of nature’s strangest creatures: an amphibian that never fully completes metamorphosis and spends its entire life in a juvenile aquatic form. Its smiling face and feathery external gills recall the Aztec god Xolotl, associated with fire and transformation, who was said to have taken its shape.','It is also a scientific marvel. The axolotl can regenerate not only limbs but parts of complex organs, including the heart and brain. Yet while laboratories around the world study this extraordinary ability, the animal has been pushed close to extinction in its own home.','The ancient canal system of Xochimilco, south of Mexico City, has been severely damaged by pollution, urbanisation and introduced species. UNAM’s Chinampa-Refugio programme works with local communities to restore cleaner, traditional aquatic refuges so the axolotl’s future does not continue only behind aquarium glass.','The portrait rests on a stark contrast: there are wounds nature can heal, but there are losses that even the greatest power of regeneration cannot reverse.'],orgs:[['UNAM — Ecological Restoration Laboratory','Habitat restoration and axolotl conservation work in Xochimilco','https://www.gaceta.unam.mx/restaurar-xochimilco-fundamental-para-conservar-el-axolote/']]},hu:{title:'Axolotl',story:['Az axolotl a természet egyik legkülönösebb teremtménye: egy kétéltű, amely sosem fejezi be teljesen az átalakulását, és egész életét fiatal, vízi alakban éli le. Mosolygó arca és tollszerű külső kopoltyúi az azték mitológia Xolotl istenét idézik, aki a történetek szerint maga is felvette ezt az alakot.','Az axolotl a tudomány egyik csodája is. Nemcsak a végtagjait, hanem összetett szervei — köztük a szíve és az agya — egyes részeit is képes regenerálni. Miközben azonban a világ laboratóriumai ezt a rendkívüli képességet kutatják, az állat a saját otthonában a kihalás szélére sodródott.','A Mexikóváros déli részén fekvő Xochimilco ősi csatornarendszerét súlyosan károsította a vízszennyezés, az urbanizáció és a betelepített fajok terjedése. Az UNAM Chinampa-Refugio programja a helyi közösségekkel együttműködve állít helyre tisztább, hagyományos vízi menedékeket, hogy az axolotl jövője ne csak az akváriumok üvegfala mögött folytatódjon.','A portré egy kemény ellentétre épül: vannak sebek, amelyeket a természet képes begyógyítani, de vannak veszteségek, amelyeket már a legerősebb regeneráció sem hozhat vissza.'],orgs:[['UNAM — Ökológiai Restaurációs Laboratórium','Élőhely-helyreállítás és axolotl-védelem Xochimilcóban','https://www.gaceta.unam.mx/restaurar-xochimilco-fundamental-para-conservar-el-axolote/']]}}
};

const staticTextHu={
 'Every drawing begins in darkness.':'Minden rajz a sötétségből indul.',
 'Light does not conclude the work.':'A fény nem lezárja a művet,',
 'It brings it to life.':'hanem életre hívja.',
 'Enter the gallery ↓':'Belépés a galériába ↓','Enter the project ↓':'Belépés a fő projektbe ↓','Skip':'Kihagyás','Skip to works':'Ugrás a művekhez',
 'Even the god of love can lose his purpose.':'Még a szerelem istene is elveszítheti a célját.',
 'Young at Heart':'Lélekben fiatal','Age changes the body, not the spirit.':'A kor a testet változtatja meg, nem a lelket.',
 'A fragile survivor with an impossible gift.':'Törékeny túlélő egy szinte lehetetlen képességgel.',
 'Pygmy Three-Toed Sloth':'Törpe háromujjú lajhár','Tapanuli Orangutan':'Tapanuli orangután','Andean Mountain Cat':'Andoki macska','Chinese Pangolin':'Kínai tobzoska','Blue-throated Macaw':'Kéktorkú ara',
 'Colored pencil & digital lightwork':'Színes ceruza és digitális fény','Mixed media':'Vegyes technika','Colored pencil':'Színes ceruza','2nd Prize':'2. helyezés',
 'I use realism to create a familiar world, then let light reveal what remains unseen: memory, vulnerability, hope and transformation.':'A realizmussal ismerős világot teremtek, majd hagyom, hogy a fény megmutassa azt, ami láthatatlan marad: az emlékezetet, a sérülékenységet, a reményt és az átalakulást.',
 'I am Magyar Levente, a self-taught Hungarian visual artist working under the name Jalraxe. My drawings combine traditional media with restrained digital illumination. The light is not added as decoration; it carries the meaning of the work.':'Magyar Levente vagyok, Jalraxe néven alkotó autodidakta magyar képzőművész. Rajzaimban a hagyományos technikát visszafogott digitális megvilágítással kapcsolom össze. A fény nem díszítés: a mű jelentését hordozza.',
 'My ongoing Guardians of Light series turns this visual language toward conservation, portraying critically endangered species as lives still visible—and therefore still possible to protect.':'A Fény Őrzői című, folyamatosan bővülő sorozatomban ezt a vizuális nyelvet a természetvédelem felé fordítom: kritikusan veszélyeztetett fajokat mutatok meg még látható — és ezért még megvédhető — életekként.',
 'His ongoing Guardians of Light series turns this visual language toward conservation, portraying critically endangered species as lives still visible—and therefore still possible to protect.':'Folyamatosan bővülő A Fény Őrzői sorozatában ezt a vizuális nyelvet a természetvédelem felé fordítja: veszélyeztetett fajokat mutat meg még látható — és ezért még megvédhető — életekként.',
 'The Last Selfie':'Az utolsó szelfi','When Life Gives You Lemons':'Ha az élet citromot ad…','Master and Muse':'A mester és a múzsa','Final Chord':'Záróakkord','Shadow of Tomorrow':'A holnap árnyéka',
 'Vigil':'Virrasztás','Witching Hour':'Boszorkányóra','Sunkissed':'Napcsókolta','Homelander':'Hazafi','Green Earring':'Zöld fülbevaló','Cigarette Break':'Cigarettaszünet',
 'Graphite & digital light study':'Grafit és digitális fénytanulmány',
 'Conceptual drawing':'Koncepciórajz','Graphite & glow':'Grafit és fény','Pastel & digital luminescence':'Pasztell és digitális fény','Traditional drawing & light':'Hagyományos rajz és fény','Chalk pastel & digital effects':'Krétapasztell és digitális effektek','Colored pencil & digital highlights':'Színes ceruza és digitális fények',
 'Back to Featured Works':'Vissza a kiemelt művekhez','Featured Work':'Kiemelt mű','Story':'Történet','Before digital light / Final':'Digitális fény előtt / Végleges','Inspiration / Final':'Inspiráció / Végleges','Details':'Részletek','Materials':'Anyagok','Final artwork':'Végleges mű','Earlier stage':'Korábbi állapot',
 'Mixed media and digital illumination':'Vegyes technika és digitális megvilágítás','Colored pencil and digital illumination':'Színes ceruza és digitális megvilágítás','Graphite and colored pencil on paper':'Grafit és színes ceruza papíron',
 '“Sometimes we do not lose our purpose at once. We simply stop reaching for the bow.”':'„Néha nem egyetlen pillanatban veszítjük el a célunkat. Egyszerűen már nem nyúlunk az íjért.”',
 '“Age changes the body, not the spirit.”':'„A kor a testet változtatja meg, nem a lelket.”',
 '“There are wounds nature can heal—and losses even regeneration cannot reverse.”':'„Vannak sebek, amelyeket a természet begyógyít — és veszteségek, amelyeket még a regeneráció sem fordíthat vissza.”'
};
Object.assign(staticTextHu,{
 'Magyar Levente (Jalraxe) is a Hungarian visual artist combining traditional drawing with digital illumination to explore vulnerability, transformation and the fragile relationship between human attention and the natural world.':'Magyar Levente (Jalraxe) magyar képzőművész, aki a hagyományos rajzot digitális fénnyel kapcsolja össze. Munkái a sérülékenységet, az átalakulást, valamint az emberi figyelem és a természeti világ törékeny kapcsolatát vizsgálják.',
 'His drawings begin with the precision and physical presence of traditional media, then use restrained digital light as a narrative element rather than decoration.':'Rajzai a hagyományos technikák pontosságából és fizikai jelenlétéből indulnak ki, majd a visszafogott digitális fényt nem díszítésként, hanem narratív elemként használják.'
});
const originalText=new WeakMap();
function translateStatic(lang){
 const walker=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT);
 let node;while((node=walker.nextNode())){if(!node.parentElement?.closest('script,style,[data-i18n]')){if(!originalText.has(node))originalText.set(node,node.nodeValue);const source=originalText.get(node),trim=source.trim();if(trim){let translated=trim;if(lang==='hu')Object.entries(staticTextHu).sort((a,b)=>b[0].length-a[0].length).forEach(([en,hu])=>translated=translated.replaceAll(en,hu));node.nodeValue=source.replace(trim,translated)}}}
 document.querySelectorAll('.story-grid').forEach(grid=>{[...grid.children].forEach((child,i)=>child.hidden=(lang==='hu'?i!==1:i!==0))});
 document.querySelectorAll('.back').forEach(link=>{const arrow=link.textContent.trim().startsWith('←')?'← ':'';const label=lang==='hu'?'Vissza a kiemelt művekhez':'Back to Featured Works';link.textContent=arrow+label});
}
function currentLang(){return document.documentElement.lang==='hu'?'hu':'en'}
function setLang(lang){localStorage.setItem('lh-lang',lang);document.documentElement.lang=lang;document.querySelectorAll('[data-i18n]').forEach(el=>{const k=el.dataset.i18n;if(translations[lang]?.[k])el.textContent=translations[lang][k]});translateStatic(lang);document.querySelector('.menu-toggle')?.setAttribute('aria-label',lang==='hu'?'Menü':'Menu');document.querySelectorAll('.lang button').forEach(b=>b.classList.toggle('active',b.dataset.lang===lang));const modal=document.querySelector('.guardian-modal.open');if(modal&&modal.dataset.currentGuardian)openGuardian(modal.dataset.currentGuardian)}
document.querySelectorAll('.lang button').forEach(b=>b.addEventListener('click',()=>setLang(b.dataset.lang)));setLang(localStorage.getItem('lh-lang')||'en');
const menuButton=document.querySelector('.menu-toggle'),nav=document.querySelector('.nav');
function closeMenu(){menuButton?.setAttribute('aria-expanded','false');nav?.classList.remove('open')}
menuButton?.addEventListener('click',()=>{const open=menuButton.getAttribute('aria-expanded')==='true';menuButton.setAttribute('aria-expanded',String(!open));nav?.classList.toggle('open',!open)});
nav?.querySelectorAll('a').forEach(a=>a.addEventListener('click',closeMenu));
const intro=document.querySelector('.intro-overlay');if(intro){const seen=sessionStorage.getItem('lh-intro');if(seen)intro.remove();else{document.body.classList.add('no-scroll');let finished=false;const finish=()=>{if(finished)return;finished=true;intro.classList.add('done');document.body.classList.remove('no-scroll');sessionStorage.setItem('lh-intro','1');setTimeout(()=>intro.remove(),950)};setTimeout(finish,9200);intro.querySelector('.intro-skip')?.addEventListener('click',finish)}}
const lb=document.querySelector('.lightbox');document.querySelectorAll('[data-lightbox]').forEach(el=>el.addEventListener('click',()=>{lb.querySelector('img').src=el.dataset.lightbox||el.src;lb.classList.add('open')}));lb?.addEventListener('click',e=>{if(e.target===lb||e.target.matches('button'))lb.classList.remove('open')});
document.querySelectorAll('.compare-range').forEach(r=>r.addEventListener('input',()=>{r.previousElementSibling.querySelector('.after').style.clipPath=`inset(0 ${100-r.value}% 0 0)`}));

const guardianModal=document.querySelector('.guardian-modal');
function openGuardian(id){if(!guardianModal||!guardianDetails[id])return;const lang=currentLang(),g=guardianDetails[id],d=g[lang];guardianModal.dataset.currentGuardian=id;guardianModal.querySelector('#guardian-modal-title').textContent=d.title;guardianModal.querySelector('.guardian-modal-latin').textContent=g.scientific;guardianModal.querySelector('.guardian-story').innerHTML=d.story.map(p=>`<p>${p}</p>`).join('');guardianModal.querySelector('.guardian-orgs').innerHTML=d.orgs.map(([name,desc,url])=>`<a class="guardian-org" href="${url}" target="_blank" rel="noopener noreferrer"><strong>${name} ↗</strong><span>${desc}</span></a>`).join('');guardianModal.classList.add('open');guardianModal.setAttribute('aria-hidden','false');document.body.classList.add('guardian-modal-open');guardianModal.querySelector('.guardian-close')?.focus()}
function closeGuardian(){if(!guardianModal)return;guardianModal.classList.remove('open');guardianModal.setAttribute('aria-hidden','true');document.body.classList.remove('guardian-modal-open')}
document.querySelectorAll('.guardian-more').forEach(b=>b.addEventListener('click',()=>openGuardian(b.dataset.guardian)));guardianModal?.querySelectorAll('[data-guardian-close]').forEach(el=>el.addEventListener('click',closeGuardian));
document.addEventListener('keydown',e=>{if(e.key==='Escape'){if(guardianModal?.classList.contains('open'))closeGuardian();else lb?.classList.remove('open')}});
